"""
nautobot_query.py
-----------------
Menu-driven Nautobot query tool.
Reads connection details from nautobotApi.cfg (generated by nautobot_setup.py).

Menu Options:
    1. Global Search      - Search all objects by any term (always partial/contains)
                            Returns: name, status, tenant, role, type, site,
                                     location, rack, primary IP
                            Drill down into any result for full device detail.

    2. Search by Device Name - Targeted device search with match type selection:
                            Starts with / Contains / Exact
                            Quick input (comma separated) or File input (one per line)

    3. Exit

CSV Export:
    Every view and drill-down offers an option to save results to a CSV file.
    Files are saved to the same directory as this script.

Requirements:
    pip install requests

Usage:
    python nautobot_query.py
"""

import csv
import configparser
import os
import sys
import urllib3
import requests
from datetime import datetime

# -------------------------------------------------------
# Suppress SSL warnings for self-signed lab certs.
# Remove if your Nautobot has a valid SSL cert.
# -------------------------------------------------------
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# -------------------------------------------------------
# Set this to your site SLUG (lowercase) not display name.
# Check Nautobot → Sites to confirm the slug value.
# This instance has a single site — set it here once.
# -------------------------------------------------------
SITE_NAME = "your-site-name"

CONFIG_FILE = "nautobotApi.cfg"


# =======================================================
# CONFIG LOADER
# =======================================================

def load_config():
    """Read URL and token from nautobotApi.cfg."""
    if not os.path.exists(CONFIG_FILE):
        print(f"\n[-] ERROR: {CONFIG_FILE} not found.")
        print("    Run nautobot_setup.py first to generate your token.")
        sys.exit(1)

    config = configparser.ConfigParser()
    config.read(CONFIG_FILE)

    try:
        url   = config["nautobot"]["url"].rstrip("/")
        token = config["nautobot"]["token"]
        return url, token
    except KeyError:
        print(f"\n[-] ERROR: {CONFIG_FILE} is missing required fields.")
        print("    Re-run nautobot_setup.py to regenerate it.")
        sys.exit(1)


# =======================================================
# NAUTOBOT API HELPERS
# =======================================================

def build_headers(token):
    """Return standard auth headers for all API calls."""
    return {
        "Authorization": f"Token {token}",
        "Accept":        "application/json",
    }


def api_get(url, token, endpoint, params=None):
    """
    GET request with automatic pagination.
    Returns a flat list of all results across all pages.

    Pass params={"limit": 0} to get all results in a single API call
    with no pagination overhead — preferred for all list views.
    """
    headers     = build_headers(token)
    all_results = []
    next_url    = f"{url}{endpoint}"

    while next_url:
        try:
            response = requests.get(
                next_url,
                headers=headers,
                params=params,
                verify=False,
                timeout=30,
            )
        except requests.exceptions.ConnectionError:
            print(f"\n[-] ERROR: Cannot reach {url}. Check network/URL.")
            return []
        except requests.exceptions.Timeout:
            print(f"\n[-] ERROR: Request timed out.")
            return []

        if response.status_code == 403:
            print(f"\n[!] 403 Forbidden on {endpoint} — check token permissions.")
            return []
        elif response.status_code == 404:
            print(f"\n[!] 404 Not Found: {endpoint} — check the endpoint path.")
            return []
        elif response.status_code != 200:
            print(f"\n[!] Unexpected HTTP {response.status_code} on {endpoint}")
            return []

        data = response.json()

        if "results" in data:
            all_results.extend(data["results"])
            next_url = data.get("next")
            params   = None
        else:
            all_results.append(data)
            break

    return all_results


def test_connection(url, token):
    """Quick connectivity and auth check on startup."""
    print(f"\n[*] Connecting to {url} ...")
    try:
        response = requests.get(
            f"{url}/api/",
            headers=build_headers(token),
            verify=False,
            timeout=10,
        )
        if response.status_code == 200:
            print(f"[+] Connected successfully.\n")
            return True
        else:
            print(f"[-] Connection failed: HTTP {response.status_code}")
            return False
    except requests.exceptions.ConnectionError:
        print(f"[-] ERROR: Cannot reach {url}.")
        return False


# =======================================================
# DISPLAY HELPERS
# =======================================================

def divider(char="=", width=60):
    print(char * width)


def section(title):
    print(f"\n  --- {title} ---")


# =======================================================
# CSV HELPERS
# =======================================================

def prompt_save_csv(rows, fieldnames, default_filename):
    """
    Prompt the user to save data to a CSV file.

    Args:
        rows             : List of dicts — one dict per row
        fieldnames       : List of column header strings
        default_filename : Suggested filename shown in the prompt

    User options:
        - Type a filename to save (.csv added automatically if missing)
        - Press Enter to skip
        - Overwrite or Append if file already exists
    """
    if not rows:
        return

    divider("-")
    print(f"\n  Save results to CSV?")
    print(f"  Suggested: {default_filename}")
    filename = input("  Enter filename or press Enter to skip: ").strip()

    if not filename:
        print("  [*] Skipped — no file saved.")
        return

    if not filename.lower().endswith(".csv"):
        filename += ".csv"

    write_mode   = "w"
    write_header = True

    if os.path.exists(filename):
        print(f"\n  [!] '{filename}' already exists.")
        action = input("  Overwrite (o) or Append (a)? ").strip().lower()
        if action == "a":
            write_mode   = "a"
            write_header = False
        elif action == "o":
            write_mode   = "w"
            write_header = True
        else:
            print("  [*] Invalid choice — skipped.")
            return

    try:
        with open(filename, write_mode, newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames,
                                    extrasaction="ignore")
            if write_header:
                writer.writeheader()
            writer.writerows(rows)

        print(f"\n  [+] Saved {len(rows)} row(s) to: {os.path.abspath(filename)}")

    except IOError as e:
        print(f"\n  [-] ERROR saving file: {e}")


# =======================================================
# SHARED: DEVICE DETAIL VIEW
# Used by both Global Search and Search by Device Name
# Returns list of CSV-ready rows for optional export
# =======================================================

# CSV column headers for device detail — used across all device exports
DEVICE_DETAIL_FIELDS = [
    "Device Name", "Status", "Platform", "Device Type", "Primary IP",
    "Rack", "RU Position", "Console Ports",
    "Interface", "Interface Type", "Enabled", "Mgmt Only", "Interface IPs",
]


def display_device_detail(url, token, device):
    """
    Print full detail for a single device:
      - Name, status, platform, device type, primary IP
      - Rack + RU position + face
      - Console ports
      - All interfaces + assigned IPs

    Returns a list of dicts (one per interface) ready for CSV export.
    """
    device_id   = device.get("id")
    device_name = device.get("name", "N/A")

    status      = device.get("status", {}).get("label", "N/A")
    platform    = device.get("platform")
    platform    = platform.get("name", "N/A") if platform else "N/A"
    device_type = device.get("device_type", {}).get("display", "N/A")
    primary_ip  = device.get("primary_ip")
    primary_ip  = primary_ip.get("address", "N/A") if primary_ip else "Not assigned"
    rack        = device.get("rack")
    rack_name   = rack.get("name", "N/A") if rack else "Not racked"
    rack_face   = device.get("face", {})
    rack_face   = rack_face.get("label", "N/A") if rack_face else "N/A"
    position    = device.get("position", "N/A")

    divider()
    print(f"  DEVICE: {device_name}")
    divider()
    print(f"  Status      : {status}")
    print(f"  Platform    : {platform}")
    print(f"  Device Type : {device_type}")
    print(f"  Primary IP  : {primary_ip}")

    section("Rack Location")
    print(f"  Rack        : {rack_name}")
    print(f"  RU Position : {position}")
    print(f"  Face        : {rack_face}")

    section("Console Ports")
    consoles      = api_get(url, token, "/api/dcim/console-ports/",
                            params={"device_id": device_id})
    console_names = []
    if consoles:
        for c in consoles:
            cname = c.get("name", "N/A")
            console_names.append(cname)
            print(f"  {cname}")
    else:
        print("  None found")

    section("Interfaces")
    interfaces = api_get(url, token, "/api/dcim/interfaces/",
                         params={"device_id": device_id})

    csv_rows = []

    if interfaces:
        for iface in interfaces:
            iface_id   = iface.get("id")
            iface_name = iface.get("name", "N/A")
            iface_type = iface.get("type", {}).get("label", "N/A")
            enabled    = "Enabled" if iface.get("enabled") else "Disabled"
            mgmt       = " [MGMT]" if iface.get("mgmt_only") else ""

            ips     = api_get(url, token, "/api/ipam/ip-addresses/",
                              params={"interface_id": iface_id})
            ip_list = ", ".join([ip.get("address", "") for ip in ips]) \
                      if ips else "No IP"

            print(f"  {iface_name:<30} {iface_type:<20} {enabled}{mgmt}")
            print(f"    IP: {ip_list}")

            csv_rows.append({
                "Device Name":    device_name,
                "Status":         status,
                "Platform":       platform,
                "Device Type":    device_type,
                "Primary IP":     primary_ip,
                "Rack":           rack_name,
                "RU Position":    position,
                "Console Ports":  ", ".join(console_names) if console_names else "None",
                "Interface":      iface_name,
                "Interface Type": iface_type,
                "Enabled":        enabled,
                "Mgmt Only":      "Yes" if iface.get("mgmt_only") else "No",
                "Interface IPs":  ip_list,
            })
    else:
        print("  None found")
        csv_rows.append({
            "Device Name":    device_name,
            "Status":         status,
            "Platform":       platform,
            "Device Type":    device_type,
            "Primary IP":     primary_ip,
            "Rack":           rack_name,
            "RU Position":    position,
            "Console Ports":  ", ".join(console_names) if console_names else "None",
            "Interface":      "N/A",
            "Interface Type": "N/A",
            "Enabled":        "N/A",
            "Mgmt Only":      "N/A",
            "Interface IPs":  "N/A",
        })

    print()
    return csv_rows


# =======================================================
# SHARED: DEVICE SUMMARY LIST + DRILL-DOWN
# Reused by both Global Search and Search by Device Name
# =======================================================

def display_summary_and_drill(url, token, devices, context_label=""):
    """
    Display a numbered summary list of devices then offer drill-down.

    Columns: #, Name, Status, Tenant, Role, Type, Site, Rack, Primary IP

    Args:
        url           : Nautobot base URL
        token         : API token
        devices       : List of device dicts from api_get()
        context_label : Optional label shown above the list (e.g. search term)

    Returns flat list of CSV-ready summary rows.
    """
    if context_label:
        print(f"\n  Results for: '{context_label}'")

    divider()
    print(f"  [+] {len(devices)} device(s) found.\n")
    print(f"  {'#':<5} {'Name':<30} {'Status':<10} {'Tenant':<15} "
          f"{'Role':<15} {'Type':<22} {'Site':<10} {'Rack':<15} {'Primary IP'}")
    divider("-")

    summary_csv_rows = []

    for idx, device in enumerate(devices, start=1):
        name       = device.get("name", "N/A")
        status     = device.get("status", {}).get("label", "N/A")

        tenant     = device.get("tenant")
        tenant     = tenant.get("name", "N/A") if tenant else "N/A"

        role       = device.get("role") or device.get("device_role")
        role       = role.get("name", "N/A") if role else "N/A"

        dtype      = device.get("device_type", {}).get("display", "N/A")

        site       = device.get("site")
        site       = site.get("name", "N/A") if site else "N/A"

        rack       = device.get("rack")
        rack       = rack.get("name", "N/A") if rack else "N/A"

        primary_ip = device.get("primary_ip")
        primary_ip = primary_ip.get("address", "N/A") if primary_ip else "N/A"

        print(f"  {idx:<5} {name:<30} {status:<10} {tenant:<15} "
              f"{role:<15} {dtype:<22} {site:<10} {rack:<15} {primary_ip}")

        summary_csv_rows.append({
            "Name":       name,
            "Status":     status,
            "Tenant":     tenant,
            "Role":       role,
            "Type":       dtype,
            "Site":       site,
            "Rack":       rack,
            "Primary IP": primary_ip,
        })

    divider()
    return summary_csv_rows


SUMMARY_FIELDS = [
    "Name", "Status", "Tenant", "Role", "Type", "Site", "Rack", "Primary IP"
]


# =======================================================
# OPTION 1 — GLOBAL SEARCH
# =======================================================

def query_global_search(url, token):
    """
    Search all devices using a contains (partial) match on name.
    Always uses name__ic — case insensitive contains.

    Displays a numbered summary list:
        Name, Status, Tenant, Role, Type, Site, Rack, Primary IP

    Offers:
        - CSV export of summary list
        - Numbered drill-down into any result for full device detail
        - CSV export of device detail
        - Returns to summary list after drill-down
    """
    while True:
        print("\n")
        divider()
        print("  Global Search")
        print("  Searches device names — partial matches always included")
        divider()

        term = input("  Enter search term or press Enter to return to menu: ").strip()

        if not term:
            return

        print(f"\n[*] Searching for devices matching: '{term}' ...")

        devices = api_get(
            url, token,
            "/api/dcim/devices/",
            params={"name__ic": term, "limit": 0},
        )

        if not devices:
            print(f"  [!] No devices found matching: '{term}'")
            input("  Press Enter to search again...")
            continue

        # Display summary list
        summary_rows = display_summary_and_drill(url, token, devices, term)

        # CSV export for summary
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        prompt_save_csv(
            rows             = summary_rows,
            fieldnames       = SUMMARY_FIELDS,
            default_filename = f"global_search_{term}_{timestamp}.csv",
        )

        # Drill-down loop — stays on summary list until user exits
        while True:
            print("\n  Enter a number to drill into a device,")
            print("  's' to search again, or press Enter to return to menu:")
            choice = input("  > ").strip().lower()

            if not choice:
                return

            if choice == "s":
                break   # back to outer search loop

            if not choice.isdigit() or not (1 <= int(choice) <= len(devices)):
                print(f"\n  [!] Invalid — enter a number between 1 "
                      f"and {len(devices)}, 's' to search again, "
                      f"or Enter to return to menu.")
                continue

            selected    = devices[int(choice) - 1]
            device_name = selected.get("name", "N/A")
            print()
            detail_rows = display_device_detail(url, token, selected)

            # CSV export for device detail
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            prompt_save_csv(
                rows             = detail_rows,
                fieldnames       = DEVICE_DETAIL_FIELDS,
                default_filename = f"device_{device_name}_{timestamp}.csv",
            )

            input("\n  Press Enter to return to search results...")

            # Redisplay summary list after returning from detail
            display_summary_and_drill(url, token, devices, term)


# =======================================================
# OPTION 2 — SEARCH BY DEVICE NAME
# =======================================================

# Nautobot filter parameters for each match type
MATCH_TYPES = {
    "1": ("name__isw", "Starts with"),
    "2": ("name__ic",  "Contains"),
    "3": ("name",      "Exact"),
}


def prompt_match_type():
    """
    Prompt user once to select a match type.
    Returns (nautobot_param, label) tuple.
    """
    print("\n  Match type:")
    print("  1. Starts with  — abc-  matches abc-spine-01, abc-leaf-01")
    print("  2. Contains     — spine matches abc-spine-01, dc-spine-02")
    print("  3. Exact        — full hostname only")
    divider("-")

    while True:
        choice = input("  Select match type (1/2/3): ").strip()
        if choice in MATCH_TYPES:
            param, label = MATCH_TYPES[choice]
            print(f"  [*] Using: {label}")
            return param, label
        print("  [!] Invalid — enter 1, 2, or 3.")


def search_devices_by_names(url, token, terms, match_param):
    """
    Shared lookup engine for Quick Search and File Search.

    Exact match   — shows full device detail immediately.
    Partial match — shows numbered summary list, then offers drill-down.

    Args:
        url         : Nautobot base URL
        token       : API token
        terms       : List of search term strings
        match_param : Nautobot filter param (name, name__isw, name__ic)

    Returns flat list of CSV-ready rows across all matched devices.
    """
    all_csv_rows = []
    found_count  = 0
    missing      = []
    is_exact     = match_param == "name"

    for term in terms:
        term = term.strip()
        if not term:
            continue

        print(f"\n[*] Searching: '{term}' ...")

        matched = api_get(url, token, "/api/dcim/devices/",
                          params={match_param: term, "limit": 0})

        if not matched:
            missing.append(term)
            print(f"  [!] No devices found for: '{term}'")
            continue

        found_count += len(matched)

        # Exact — full detail immediately
        if is_exact:
            rows = display_device_detail(url, token, matched[0])
            all_csv_rows.extend(rows)

        # Partial — summary list with drill-down
        else:
            summary_rows = display_summary_and_drill(
                url, token, matched, term
            )

            # CSV export for this term's summary
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            prompt_save_csv(
                rows             = summary_rows,
                fieldnames       = SUMMARY_FIELDS,
                default_filename = f"search_{term}_{timestamp}.csv",
            )

            # Drill-down
            while True:
                print(f"\n  Enter a number to drill into a device,")
                drill = input(
                    "  or press Enter to continue to next term: "
                ).strip()

                if not drill:
                    break

                if not drill.isdigit() or \
                   not (1 <= int(drill) <= len(matched)):
                    print(f"\n  [!] Invalid — enter a number between "
                          f"1 and {len(matched)}.")
                    continue

                selected    = matched[int(drill) - 1]
                device_name = selected.get("name", "N/A")
                print()
                detail_rows = display_device_detail(url, token, selected)
                all_csv_rows.extend(detail_rows)

                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                prompt_save_csv(
                    rows             = detail_rows,
                    fieldnames       = DEVICE_DETAIL_FIELDS,
                    default_filename = f"device_{device_name}_{timestamp}.csv",
                )

                input("\n  Press Enter to return to match list...")

                # Redisplay summary after returning from detail
                display_summary_and_drill(url, token, matched, term)

    # Final summary
    divider()
    print(f"  Search complete.")
    print(f"  Matched : {found_count} device(s)")
    if missing:
        print(f"  No results for {len(missing)} term(s):")
        for m in missing:
            print(f"            - {m}")
    divider()

    return all_csv_rows


def query_search_by_name(url, token):
    """
    Sub-menu for targeted device search.
    Two input methods:
        1. Quick Search — comma separated terms
        2. File Search  — one term per line, # lines ignored
    Match type selected once per search session.
    """
    while True:
        print("\n")
        divider()
        print("  Search by Device Name")
        divider()
        print("  1. Quick Search  — paste terms (comma separated)")
        print("  2. File Search   — load from text file (one per line)")
        print("  3. Back to main menu")
        divider()

        choice = input("  Select an option: ").strip()

        # ---------------------------------------------------
        # Quick Search
        # ---------------------------------------------------
        if choice == "1":
            print("\n  Paste search terms separated by commas.")
            raw = input("  Terms: ").strip()

            if not raw:
                print("  [!] No input provided.")
                continue

            terms = [t.strip() for t in raw.split(",") if t.strip()]

            if not terms:
                print("  [!] No valid terms found.")
                continue

            match_param, match_label = prompt_match_type()

            print(f"\n[*] Quick Search — {len(terms)} term(s) "
                  f"using '{match_label}' matching.")

            all_csv_rows = search_devices_by_names(
                url, token, terms, match_param
            )

            if all_csv_rows:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                prompt_save_csv(
                    rows             = all_csv_rows,
                    fieldnames       = DEVICE_DETAIL_FIELDS,
                    default_filename = f"search_results_{timestamp}.csv",
                )

            input("\n  Press Enter to return to search menu...")

        # ---------------------------------------------------
        # File Search
        # ---------------------------------------------------
        elif choice == "2":
            print("\n  Enter the full path to your search terms file.")
            print("  File format: one term per line, # lines are ignored.")
            filepath = input("  File path: ").strip().strip('"')

            if not filepath:
                print("  [!] No file path provided.")
                continue

            if not os.path.exists(filepath):
                print(f"  [-] File not found: {filepath}")
                print("      Check the path and try again.")
                continue

            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    terms = [
                        line.strip()
                        for line in f.readlines()
                        if line.strip()
                        and not line.startswith("#")
                    ]
            except IOError as e:
                print(f"  [-] ERROR reading file: {e}")
                continue

            if not terms:
                print("  [!] File is empty or contains no valid terms.")
                continue

            match_param, match_label = prompt_match_type()

            print(f"\n[*] File Search — {len(terms)} term(s) from "
                  f"'{os.path.basename(filepath)}' "
                  f"using '{match_label}' matching.")

            all_csv_rows = search_devices_by_names(
                url, token, terms, match_param
            )

            if all_csv_rows:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                prompt_save_csv(
                    rows             = all_csv_rows,
                    fieldnames       = DEVICE_DETAIL_FIELDS,
                    default_filename = f"search_results_{timestamp}.csv",
                )

            input("\n  Press Enter to return to search menu...")

        # ---------------------------------------------------
        # Back to main menu
        # ---------------------------------------------------
        elif choice == "3":
            return

        else:
            print("\n  [!] Invalid selection. Enter 1, 2, or 3.")


# =======================================================
# MAIN MENU
# =======================================================

def main_menu():
    while True:
        print("\n")
        divider()
        print("  Nautobot Query Tool")
        print(f"  Site: {SITE_NAME}")
        divider()
        print("  1. Global Search")
        print("  2. Search by Device Name")
        print("  3. Exit")
        divider()

        choice = input("  Select an option: ").strip()

        if choice == "1":
            query_global_search(url, token)
        elif choice == "2":
            query_search_by_name(url, token)
        elif choice == "3":
            print("\n  Goodbye.\n")
            sys.exit(0)
        else:
            print("\n  [!] Invalid selection. Enter 1, 2, or 3.")


# =======================================================
# ENTRY POINT
# =======================================================

if __name__ == "__main__":
    url, token = load_config()

    if not test_connection(url, token):
        print("[-] Could not connect to Nautobot. Check your config and network.")
        sys.exit(1)

    main_menu()
