"""
nautobot_query.py
-----------------
Menu-driven Nautobot query tool.
Reads connection details from nautobotApi.cfg (generated by nautobot_setup.py).

Menu Options:
    1. Devices        - Full detail: interfaces, IPs, console, rack, RU
    2. IP Addresses   - All IPs at site with optional drill-down into device
    3. Racks          - All racks with devices and RU positions
    4. Exit

Requirements:
    pip install requests

Usage:
    python nautobot_query.py
"""

import requests
import configparser
import os
import sys
import urllib3

# -------------------------------------------------------
# Suppress SSL warnings for self-signed lab certs.
# Remove if your Nautobot has a valid SSL cert.
# -------------------------------------------------------
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# -------------------------------------------------------
# Edit this variable to match your site name in Nautobot.
# This instance has a single site — set it here once.
# -------------------------------------------------------
SITE_NAME = "your-site-name"

CONFIG_FILE = "nautobotApi.cfg"


# =======================================================
# CONFIG LOADER
# =======================================================

def load_config():
    """Read URL and token from nautobotApi.cfg."""
    if not os.path.exists(CONFIG_FILE):
        print(f"\n[-] ERROR: {CONFIG_FILE} not found.")
        print("    Run nautobot_setup.py first to generate your token.")
        sys.exit(1)

    config = configparser.ConfigParser()
    config.read(CONFIG_FILE)

    try:
        url   = config["nautobot"]["url"].rstrip("/")
        token = config["nautobot"]["token"]
        return url, token
    except KeyError:
        print(f"\n[-] ERROR: {CONFIG_FILE} is missing required fields.")
        print("    Re-run nautobot_setup.py to regenerate it.")
        sys.exit(1)


# =======================================================
# NAUTOBOT API HELPERS
# =======================================================

def build_headers(token):
    """Return standard auth headers for all API calls."""
    return {
        "Authorization": f"Token {token}",
        "Accept":        "application/json",
    }


def api_get(url, token, endpoint, params=None):
    """
    GET request with automatic pagination.
    Returns a flat list of all results across all pages.
    """
    headers     = build_headers(token)
    all_results = []
    next_url    = f"{url}{endpoint}"

    while next_url:
        try:
            response = requests.get(
                next_url,
                headers=headers,
                params=params,
                verify=False,
                timeout=15,
            )
        except requests.exceptions.ConnectionError:
            print(f"\n[-] ERROR: Cannot reach {url}. Check network/URL.")
            return []
        except requests.exceptions.Timeout:
            print(f"\n[-] ERROR: Request timed out.")
            return []

        if response.status_code == 403:
            print(f"\n[!] 403 Forbidden on {endpoint} — check token permissions.")
            return []
        elif response.status_code == 404:
            print(f"\n[!] 404 Not Found: {endpoint} — check the endpoint path.")
            return []
        elif response.status_code != 200:
            print(f"\n[!] Unexpected HTTP {response.status_code} on {endpoint}")
            return []

        data = response.json()

        if "results" in data:
            all_results.extend(data["results"])
            next_url = data.get("next")   # None when last page reached
            params   = None               # Params already baked into next_url
        else:
            all_results.append(data)
            break

    return all_results


def test_connection(url, token):
    """Quick connectivity and auth check on startup."""
    print(f"\n[*] Connecting to {url} ...")
    try:
        response = requests.get(
            f"{url}/api/",
            headers=build_headers(token),
            verify=False,
            timeout=10,
        )
        if response.status_code == 200:
            print(f"[+] Connected successfully.\n")
            return True
        else:
            print(f"[-] Connection failed: HTTP {response.status_code}")
            return False
    except requests.exceptions.ConnectionError:
        print(f"[-] ERROR: Cannot reach {url}.")
        return False


# =======================================================
# DISPLAY HELPERS
# =======================================================

def divider(char="=", width=60):
    print(char * width)


def section(title):
    print(f"\n  --- {title} ---")


# =======================================================
# SHARED: DEVICE DETAIL VIEW
# Used by both Option 1 and Option 2 drill-down
# =======================================================

def display_device_detail(url, token, device):
    """
    Print full detail for a single device:
    - Name, status, platform, device type
    - Primary IP
    - All interfaces + assigned IPs
    - Console port
    - Rack + RU position
    """
    device_id   = device.get("id")
    device_name = device.get("name", "N/A")

    divider()
    print(f"  DEVICE: {device_name}")
    divider()

    # Basic info
    status      = device.get("status", {}).get("label", "N/A")
    platform    = device.get("platform")
    platform    = platform.get("name", "N/A") if platform else "N/A"
    device_type = device.get("device_type", {}).get("display", "N/A")
    primary_ip  = device.get("primary_ip")
    primary_ip  = primary_ip.get("address", "N/A") if primary_ip else "Not assigned"

    print(f"  Status      : {status}")
    print(f"  Platform    : {platform}")
    print(f"  Device Type : {device_type}")
    print(f"  Primary IP  : {primary_ip}")

    # Rack + RU position
    section("Rack Location")
    rack         = device.get("rack")
    rack_name    = rack.get("name", "N/A") if rack else "Not racked"
    rack_face    = device.get("face", {})
    rack_face    = rack_face.get("label", "N/A") if rack_face else "N/A"
    position     = device.get("position", "N/A")

    print(f"  Rack         : {rack_name}")
    print(f"  RU Position  : {position}")
    print(f"  Face         : {rack_face}")

    # Console ports
    section("Console Ports")
    consoles = api_get(url, token, f"/api/dcim/console-ports/", params={"device_id": device_id})
    if consoles:
        for c in consoles:
            print(f"  {c.get('name', 'N/A')}")
    else:
        print("  None found")

    # Interfaces + IPs
    section("Interfaces")
    interfaces = api_get(url, token, "/api/dcim/interfaces/", params={"device_id": device_id})

    if interfaces:
        for iface in interfaces:
            iface_id   = iface.get("id")
            iface_name = iface.get("name", "N/A")
            iface_type = iface.get("type", {}).get("label", "N/A")
            enabled    = "Enabled" if iface.get("enabled") else "Disabled"
            mgmt       = " [MGMT]" if iface.get("mgmt_only") else ""

            # Get IPs assigned to this interface
            ips = api_get(url, token, "/api/ipam/ip-addresses/",
                          params={"interface_id": iface_id})
            ip_list = ", ".join([ip.get("address", "") for ip in ips]) if ips else "No IP"

            print(f"  {iface_name:<30} {iface_type:<20} {enabled}{mgmt}")
            print(f"  {'':>2}IP: {ip_list}")
    else:
        print("  None found")

    print()


# =======================================================
# OPTION 1 — DEVICES
# =======================================================

def query_devices(url, token):
    """Pull all devices at SITE_NAME and display full detail."""
    print(f"\n[*] Fetching all devices at site: {SITE_NAME} ...")

    devices = api_get(url, token, "/api/dcim/devices/", params={"site": SITE_NAME})

    if not devices:
        print(f"[!] No devices found for site: {SITE_NAME}")
        print("    Check that SITE_NAME matches exactly what's in Nautobot.")
        return

    print(f"[+] Found {len(devices)} device(s).\n")

    for device in devices:
        display_device_detail(url, token, device)

    input("  Press Enter to return to menu...")


# =======================================================
# OPTION 2 — IP ADDRESSES
# =======================================================

def query_ip_addresses(url, token):
    """
    Pull all IPs at SITE_NAME.
    After display, optionally drill down into a device
    using the shared display_device_detail() function.
    """
    print(f"\n[*] Fetching all IP addresses at site: {SITE_NAME} ...")

    ips = api_get(url, token, "/api/ipam/ip-addresses/", params={"site": SITE_NAME})

    if not ips:
        print(f"[!] No IP addresses found for site: {SITE_NAME}")
        return

    print(f"[+] Found {len(ips)} IP address(es).\n")
    divider()
    print(f"  {'IP Address':<25} {'Device':<30} {'Interface'}")
    divider("-")

    for ip in ips:
        address   = ip.get("address", "N/A")
        interface = ip.get("assigned_object")

        if interface:
            device_name = interface.get("device", {}).get("name", "N/A") \
                if interface.get("device") else "N/A"
            iface_name  = interface.get("name", "N/A")
        else:
            device_name = "Unassigned"
            iface_name  = "N/A"

        print(f"  {address:<25} {device_name:<30} {iface_name}")

    divider()

    # Drill-down option
    print("\n  Enter a device name to drill down into it,")
    choice = input("  or press Enter to return to menu: ").strip()

    if choice:
        # Look up the device by name and show full detail
        matched = api_get(url, token, "/api/dcim/devices/", params={"name": choice})
        if matched:
            print()
            display_device_detail(url, token, matched[0])
        else:
            print(f"\n[!] No device found with name: {choice}")

    input("  Press Enter to return to menu...")


# =======================================================
# OPTION 3 — RACKS
# =======================================================

def query_racks(url, token):
    """
    Pull all racks at SITE_NAME.
    For each rack, list every device and its RU position.
    """
    print(f"\n[*] Fetching all racks at site: {SITE_NAME} ...")

    racks = api_get(url, token, "/api/dcim/racks/", params={"site": SITE_NAME})

    if not racks:
        print(f"[!] No racks found for site: {SITE_NAME}")
        return

    print(f"[+] Found {len(racks)} rack(s).\n")

    for rack in racks:
        rack_id       = rack.get("id")
        rack_name     = rack.get("name", "N/A")
        rack_location = rack.get("location")
        rack_location = rack_location.get("name", "N/A") if rack_location else "N/A"
        rack_height   = rack.get("u_height", "N/A")
        rack_status   = rack.get("status", {}).get("label", "N/A")

        divider()
        print(f"  RACK : {rack_name}")
        divider("-")
        print(f"  Location  : {rack_location}")
        print(f"  Height    : {rack_height}U")
        print(f"  Status    : {rack_status}")

        # Get all devices in this rack
        devices = api_get(url, token, "/api/dcim/devices/",
                          params={"rack_id": rack_id})

        section("Devices in Rack")
        if devices:
            print(f"  {'RU':<6} {'Device Name':<35} {'Device Type':<30} {'Status'}")
            divider("-")
            # Sort by RU position so rack reads top to bottom
            devices_sorted = sorted(
                devices,
                key=lambda d: d.get("position") or 0,
                reverse=True
            )
            for d in devices_sorted:
                position    = str(d.get("position", "N/A"))
                name        = d.get("name", "N/A")
                dtype       = d.get("device_type", {}).get("display", "N/A")
                status      = d.get("status", {}).get("label", "N/A")
                print(f"  {position:<6} {name:<35} {dtype:<30} {status}")
        else:
            print("  No devices found in this rack.")

        print()

    input("  Press Enter to return to menu...")


# =======================================================
# MAIN MENU
# =======================================================

def main_menu():
    while True:
        print("\n")
        divider()
        print("  Nautobot Query Tool")
        print(f"  Site: {SITE_NAME}")
        divider()
        print("  1. Devices")
        print("  2. IP Addresses")
        print("  3. Racks")
        print("  4. Exit")
        divider()

        choice = input("  Select an option: ").strip()

        if choice == "1":
            query_devices(url, token)
        elif choice == "2":
            query_ip_addresses(url, token)
        elif choice == "3":
            query_racks(url, token)
        elif choice == "4":
            print("\n  Goodbye.\n")
            sys.exit(0)
        else:
            print("\n  [!] Invalid selection. Please enter 1, 2, 3, or 4.")


# =======================================================
# ENTRY POINT
# =======================================================

if __name__ == "__main__":
    url, token = load_config()

    if not test_connection(url, token):
        print("[-] Could not connect to Nautobot. Check your config and network.")
        sys.exit(1)

    main_menu()
