"""
nautobot_query.py
-----------------
Menu-driven Nautobot query tool.
Reads connection details from nautobotApi.cfg (generated by nautobot_setup.py).

Menu Options:
    1. Devices        - Summary list first, drill down into single device for full detail
    2. IP Addresses   - All IPs at site with optional drill-down into device
    3. Racks          - Summary list first, drill down into single rack for device detail
    4. Platforms      - All platforms with drill-down into devices per platform
    5. Search by Device Name - Quick (comma separated) or File (one per line)
    6. Exit

CSV Export:
    Every view and drill-down offers an option to save results to a CSV file.
    Files are saved to the same directory as this script.

Requirements:
    pip install requests

Usage:
    python nautobot_query.py
"""

import csv
import configparser
import os
import sys
import urllib3
import requests
from datetime import datetime

# -------------------------------------------------------
# Suppress SSL warnings for self-signed lab certs.
# Remove if your Nautobot has a valid SSL cert.
# -------------------------------------------------------
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# -------------------------------------------------------
# Edit this variable to match your site name in Nautobot.
# This instance has a single site — set it here once.
# -------------------------------------------------------
SITE_NAME = "your-site-name"

CONFIG_FILE = "nautobotApi.cfg"


# =======================================================
# CONFIG LOADER
# =======================================================

def load_config():
    """Read URL and token from nautobotApi.cfg."""
    if not os.path.exists(CONFIG_FILE):
        print(f"\n[-] ERROR: {CONFIG_FILE} not found.")
        print("    Run nautobot_setup.py first to generate your token.")
        sys.exit(1)

    config = configparser.ConfigParser()
    config.read(CONFIG_FILE)

    try:
        url   = config["nautobot"]["url"].rstrip("/")
        token = config["nautobot"]["token"]
        return url, token
    except KeyError:
        print(f"\n[-] ERROR: {CONFIG_FILE} is missing required fields.")
        print("    Re-run nautobot_setup.py to regenerate it.")
        sys.exit(1)


# =======================================================
# NAUTOBOT API HELPERS
# =======================================================

def build_headers(token):
    """Return standard auth headers for all API calls."""
    return {
        "Authorization": f"Token {token}",
        "Accept":        "application/json",
    }


def api_get(url, token, endpoint, params=None):
    """
    GET request with automatic pagination.
    Returns a flat list of all results across all pages.

    Performance tip: pass params={"limit": 0} to request all results
    in a single API call — Nautobot returns everything at once with no
    pagination overhead. Use for summary list views.
    """
    headers     = build_headers(token)
    all_results = []
    next_url    = f"{url}{endpoint}"

    while next_url:
        try:
            response = requests.get(
                next_url,
                headers=headers,
                params=params,
                verify=False,
                timeout=30,        # increased from 15 for large result sets
            )
        except requests.exceptions.ConnectionError:
            print(f"\n[-] ERROR: Cannot reach {url}. Check network/URL.")
            return []
        except requests.exceptions.Timeout:
            print(f"\n[-] ERROR: Request timed out.")
            return []

        if response.status_code == 403:
            print(f"\n[!] 403 Forbidden on {endpoint} — check token permissions.")
            return []
        elif response.status_code == 404:
            print(f"\n[!] 404 Not Found: {endpoint} — check the endpoint path.")
            return []
        elif response.status_code != 200:
            print(f"\n[!] Unexpected HTTP {response.status_code} on {endpoint}")
            return []

        data = response.json()

        if "results" in data:
            all_results.extend(data["results"])
            next_url = data.get("next")   # None when last page reached
            params   = None               # Params already baked into next_url
        else:
            # Single object endpoint — wrap in list for consistency
            all_results.append(data)
            break

    return all_results


def test_connection(url, token):
    """Quick connectivity and auth check on startup."""
    print(f"\n[*] Connecting to {url} ...")
    try:
        response = requests.get(
            f"{url}/api/",
            headers=build_headers(token),
            verify=False,
            timeout=10,
        )
        if response.status_code == 200:
            print(f"[+] Connected successfully.\n")
            return True
        else:
            print(f"[-] Connection failed: HTTP {response.status_code}")
            return False
    except requests.exceptions.ConnectionError:
        print(f"[-] ERROR: Cannot reach {url}.")
        return False


# =======================================================
# DISPLAY HELPERS
# =======================================================

def divider(char="=", width=60):
    print(char * width)


def section(title):
    print(f"\n  --- {title} ---")


# =======================================================
# CSV HELPERS
# =======================================================

def prompt_save_csv(rows, fieldnames, default_filename):
    """
    Prompt the user to save data to a CSV file.

    Args:
        rows             : List of dicts — one dict per row
        fieldnames       : List of column header strings
        default_filename : Suggested filename shown in the prompt

    The user can:
        - Type a filename to save (.csv added automatically if missing)
        - Press Enter to skip saving entirely
        - Choose to overwrite or append if the file already exists
    """
    if not rows:
        return

    divider("-")
    print(f"\n  Save results to CSV?")
    print(f"  Suggested: {default_filename}")
    filename = input("  Enter filename or press Enter to skip: ").strip()

    if not filename:
        print("  [*] Skipped — no file saved.")
        return

    # Ensure .csv extension
    if not filename.lower().endswith(".csv"):
        filename += ".csv"

    # Handle existing file
    write_mode   = "w"
    write_header = True

    if os.path.exists(filename):
        print(f"\n  [!] '{filename}' already exists.")
        action = input("  Overwrite (o) or Append (a)? ").strip().lower()
        if action == "a":
            write_mode   = "a"
            write_header = False
        elif action == "o":
            write_mode   = "w"
            write_header = True
        else:
            print("  [*] Invalid choice — skipped, no file saved.")
            return

    try:
        with open(filename, write_mode, newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
            if write_header:
                writer.writeheader()
            writer.writerows(rows)

        full_path = os.path.abspath(filename)
        print(f"\n  [+] Saved {len(rows)} row(s) to: {full_path}")

    except IOError as e:
        print(f"\n  [-] ERROR saving file: {e}")


# =======================================================
# SHARED: DEVICE DETAIL VIEW
# Used by Options 1, 2, and 4 drill-downs
# Returns a list of CSV-ready rows for optional export
# =======================================================

# CSV column headers for device detail — used across all device exports
DEVICE_DETAIL_FIELDS = [
    "Device Name", "Status", "Platform", "Device Type", "Primary IP",
    "Rack", "RU Position", "Console Ports",
    "Interface", "Interface Type", "Enabled", "Mgmt Only", "Interface IPs",
]


def display_device_detail(url, token, device):
    """
    Print full detail for a single device:
      - Name, status, platform, device type
      - Primary IP
      - Rack + RU position
      - Console ports
      - All interfaces + assigned IPs

    Returns a list of dicts (one per interface) ready for CSV export.
    """
    device_id   = device.get("id")
    device_name = device.get("name", "N/A")

    # Basic info
    status      = device.get("status", {}).get("label", "N/A")
    platform    = device.get("platform")
    platform    = platform.get("name", "N/A") if platform else "N/A"
    device_type = device.get("device_type", {}).get("display", "N/A")
    primary_ip  = device.get("primary_ip")
    primary_ip  = primary_ip.get("address", "N/A") if primary_ip else "Not assigned"

    # Rack info
    rack      = device.get("rack")
    rack_name = rack.get("name", "N/A") if rack else "Not racked"
    rack_face = device.get("face", {})
    rack_face = rack_face.get("label", "N/A") if rack_face else "N/A"
    position  = device.get("position", "N/A")

    divider()
    print(f"  DEVICE: {device_name}")
    divider()
    print(f"  Status      : {status}")
    print(f"  Platform    : {platform}")
    print(f"  Device Type : {device_type}")
    print(f"  Primary IP  : {primary_ip}")

    section("Rack Location")
    print(f"  Rack        : {rack_name}")
    print(f"  RU Position : {position}")
    print(f"  Face        : {rack_face}")

    # Console ports
    section("Console Ports")
    consoles      = api_get(url, token, "/api/dcim/console-ports/",
                            params={"device_id": device_id})
    console_names = []
    if consoles:
        for c in consoles:
            cname = c.get("name", "N/A")
            console_names.append(cname)
            print(f"  {cname}")
    else:
        print("  None found")

    # Interfaces + IPs
    section("Interfaces")
    interfaces = api_get(url, token, "/api/dcim/interfaces/",
                         params={"device_id": device_id})

    csv_rows = []

    if interfaces:
        for iface in interfaces:
            iface_id   = iface.get("id")
            iface_name = iface.get("name", "N/A")
            iface_type = iface.get("type", {}).get("label", "N/A")
            enabled    = "Enabled" if iface.get("enabled") else "Disabled"
            mgmt       = " [MGMT]" if iface.get("mgmt_only") else ""

            ips     = api_get(url, token, "/api/ipam/ip-addresses/",
                              params={"interface_id": iface_id})
            ip_list = ", ".join([ip.get("address", "") for ip in ips]) \
                      if ips else "No IP"

            print(f"  {iface_name:<30} {iface_type:<20} {enabled}{mgmt}")
            print(f"    IP: {ip_list}")

            csv_rows.append({
                "Device Name":    device_name,
                "Status":         status,
                "Platform":       platform,
                "Device Type":    device_type,
                "Primary IP":     primary_ip,
                "Rack":           rack_name,
                "RU Position":    position,
                "Console Ports":  ", ".join(console_names) if console_names else "None",
                "Interface":      iface_name,
                "Interface Type": iface_type,
                "Enabled":        enabled,
                "Mgmt Only":      "Yes" if iface.get("mgmt_only") else "No",
                "Interface IPs":  ip_list,
            })
    else:
        print("  None found")
        # One row with device info even if no interfaces
        csv_rows.append({
            "Device Name":    device_name,
            "Status":         status,
            "Platform":       platform,
            "Device Type":    device_type,
            "Primary IP":     primary_ip,
            "Rack":           rack_name,
            "RU Position":    position,
            "Console Ports":  ", ".join(console_names) if console_names else "None",
            "Interface":      "N/A",
            "Interface Type": "N/A",
            "Enabled":        "N/A",
            "Mgmt Only":      "N/A",
            "Interface IPs":  "N/A",
        })

    print()
    return csv_rows


# =======================================================
# OPTION 1 — DEVICES
# =======================================================

def query_devices(url, token):
    """
    Stage 1 — Single API call pulls all devices at SITE_NAME.
              Displays a fast numbered summary list.
              CSV export available from summary.
    Stage 2 — User selects a number to drill into full device detail.
              Additional API calls made only for the selected device.
              CSV export available from detail view.
              Returns to summary list after detail — not main menu.
    """
    while True:
        print(f"\n[*] Fetching all devices at site: {SITE_NAME} ...")

        devices = api_get(url, token, "/api/dcim/devices/",
                          params={"site": SITE_NAME, "limit": 0})

        if not devices:
            print(f"[!] No devices found for site: {SITE_NAME}")
            print("    Check that SITE_NAME slug is correct (lowercase).")
            input("  Press Enter to return to menu...")
            return

        print(f"[+] Found {len(devices)} device(s).\n")
        divider()
        print(f"  {'#':<5} {'Device Name':<35} {'Status':<12} "
              f"{'Platform':<20} {'Rack':<20} {'RU'}")
        divider("-")

        # Build summary CSV rows while printing
        summary_csv_rows = []
        for idx, device in enumerate(devices, start=1):
            name       = device.get("name", "N/A")
            status     = device.get("status", {}).get("label", "N/A")
            platform   = device.get("platform")
            platform   = platform.get("name", "N/A") if platform else "N/A"
            rack       = device.get("rack")
            rack_name  = rack.get("name", "N/A") if rack else "Not racked"
            position   = str(device.get("position", "N/A"))
            primary_ip = device.get("primary_ip")
            primary_ip = primary_ip.get("address", "N/A") \
                         if primary_ip else "Not assigned"

            print(f"  {idx:<5} {name:<35} {status:<12} "
                  f"{platform:<20} {rack_name:<20} {position}")

            summary_csv_rows.append({
                "Device Name": name,
                "Status":      status,
                "Platform":    platform,
                "Primary IP":  primary_ip,
                "Rack":        rack_name,
                "RU Position": position,
            })

        divider()

        # CSV export for summary list
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        prompt_save_csv(
            rows             = summary_csv_rows,
            fieldnames       = [
                "Device Name", "Status", "Platform",
                "Primary IP", "Rack", "RU Position"
            ],
            default_filename = f"devices_summary_{SITE_NAME}_{timestamp}.csv",
        )

        # Drill-down prompt
        print("\n  Enter a number for full detail,")
        choice = input("  or press Enter to return to menu: ").strip()

        if not choice:
            return

        if not choice.isdigit() or not (1 <= int(choice) <= len(devices)):
            print(f"\n[!] Invalid selection. Enter a number between "
                  f"1 and {len(devices)}.")
            continue

        selected_device = devices[int(choice) - 1]
        device_name     = selected_device.get("name", "N/A")
        print()
        detail_rows = display_device_detail(url, token, selected_device)

        # CSV export for device detail
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        prompt_save_csv(
            rows             = detail_rows,
            fieldnames       = DEVICE_DETAIL_FIELDS,
            default_filename = f"device_{device_name}_{timestamp}.csv",
        )

        input("\n  Press Enter to return to device list...")


# =======================================================
# OPTION 2 — IP ADDRESSES
# =======================================================

def query_ip_addresses(url, token):
    """
    Pull all IPs at SITE_NAME.
    CSV export offered after list view and after device drill-down.
    """
    print(f"\n[*] Fetching all IP addresses at site: {SITE_NAME} ...")

    ips = api_get(url, token, "/api/ipam/ip-addresses/",
                  params={"site": SITE_NAME, "limit": 0})

    if not ips:
        print(f"[!] No IP addresses found for site: {SITE_NAME}")
        input("  Press Enter to return to menu...")
        return

    print(f"[+] Found {len(ips)} IP address(es).\n")
    divider()
    print(f"  {'IP Address':<25} {'Device':<30} {'Interface'}")
    divider("-")

    csv_rows = []
    for ip in ips:
        address   = ip.get("address", "N/A")
        interface = ip.get("assigned_object")

        if interface:
            device_name = interface.get("device", {}).get("name", "N/A") \
                if interface.get("device") else "N/A"
            iface_name  = interface.get("name", "N/A")
        else:
            device_name = "Unassigned"
            iface_name  = "N/A"

        print(f"  {address:<25} {device_name:<30} {iface_name}")
        csv_rows.append({
            "IP Address": address,
            "Device":     device_name,
            "Interface":  iface_name,
        })

    divider()

    # CSV export for IP list
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    prompt_save_csv(
        rows             = csv_rows,
        fieldnames       = ["IP Address", "Device", "Interface"],
        default_filename = f"ip_addresses_{SITE_NAME}_{timestamp}.csv",
    )

    # Optional device drill-down
    print("\n  Enter a device name to drill down into it,")
    choice = input("  or press Enter to return to menu: ").strip()

    if choice:
        matched = api_get(url, token, "/api/dcim/devices/", params={"name": choice})
        if matched:
            print()
            detail_rows = display_device_detail(url, token, matched[0])

            # CSV export for device drill-down
            prompt_save_csv(
                rows             = detail_rows,
                fieldnames       = DEVICE_DETAIL_FIELDS,
                default_filename = f"device_{choice}_{timestamp}.csv",
            )
        else:
            print(f"\n[!] No device found with name: {choice}")

    input("\n  Press Enter to return to menu...")


# =======================================================
# OPTION 3 — RACKS
# =======================================================

def query_racks(url, token):
    """
    Stage 1 — Single API call pulls all racks at SITE_NAME.
              Displays a fast numbered summary list.
              CSV export available from summary.
    Stage 2 — User selects a rack number to see all devices in it.
              Additional API call made only for the selected rack.
              Devices sorted by RU position top to bottom.
              CSV export available from rack detail.
              Returns to rack list after — not main menu.
    """
    while True:
        print(f"\n[*] Fetching all racks at site: {SITE_NAME} ...")

        racks = api_get(url, token, "/api/dcim/racks/",
                        params={"site": SITE_NAME, "limit": 0})

        if not racks:
            print(f"[!] No racks found for site: {SITE_NAME}")
            input("  Press Enter to return to menu...")
            return

        print(f"[+] Found {len(racks)} rack(s).\n")
        divider()
        print(f"  {'#':<5} {'Rack Name':<30} {'Location':<25} "
              f"{'Height':<8} {'Status'}")
        divider("-")

        summary_csv_rows = []
        for idx, rack in enumerate(racks, start=1):
            rack_name     = rack.get("name", "N/A")
            rack_location = rack.get("location")
            rack_location = rack_location.get("name", "N/A") \
                            if rack_location else "N/A"
            rack_height   = rack.get("u_height", "N/A")
            rack_status   = rack.get("status", {}).get("label", "N/A")

            print(f"  {idx:<5} {rack_name:<30} {rack_location:<25} "
                  f"{str(rack_height) + 'U':<8} {rack_status}")

            summary_csv_rows.append({
                "Rack":        rack_name,
                "Location":    rack_location,
                "Rack Height": f"{rack_height}U",
                "Rack Status": rack_status,
            })

        divider()

        # CSV export for rack summary
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        prompt_save_csv(
            rows             = summary_csv_rows,
            fieldnames       = ["Rack", "Location", "Rack Height", "Rack Status"],
            default_filename = f"racks_summary_{SITE_NAME}_{timestamp}.csv",
        )

        # Drill-down prompt
        print("\n  Enter a number to see devices in a rack,")
        choice = input("  or press Enter to return to menu: ").strip()

        if not choice:
            return

        if not choice.isdigit() or not (1 <= int(choice) <= len(racks)):
            print(f"\n[!] Invalid selection. Enter a number between "
                  f"1 and {len(racks)}.")
            continue

        selected_rack = racks[int(choice) - 1]
        rack_id       = selected_rack.get("id")
        rack_name     = selected_rack.get("name", "N/A")
        rack_location = selected_rack.get("location")
        rack_location = rack_location.get("name", "N/A") \
                        if rack_location else "N/A"
        rack_height   = selected_rack.get("u_height", "N/A")
        rack_status   = selected_rack.get("status", {}).get("label", "N/A")

        print(f"\n[*] Fetching devices in rack: {rack_name} ...")
        devices = api_get(url, token, "/api/dcim/devices/",
                          params={"rack_id": rack_id})

        divider()
        print(f"  RACK : {rack_name}")
        divider("-")
        print(f"  Location  : {rack_location}")
        print(f"  Height    : {rack_height}U")
        print(f"  Status    : {rack_status}")

        section("Devices in Rack")

        rack_csv_rows = []
        if devices:
            print(f"  {'RU':<6} {'Device Name':<35} "
                  f"{'Device Type':<30} {'Status'}")
            divider("-")

            devices_sorted = sorted(
                devices,
                key=lambda d: d.get("position") or 0,
                reverse=True,
            )
            for d in devices_sorted:
                position = str(d.get("position", "N/A"))
                name     = d.get("name", "N/A")
                dtype    = d.get("device_type", {}).get("display", "N/A")
                dstatus  = d.get("status", {}).get("label", "N/A")
                print(f"  {position:<6} {name:<35} {dtype:<30} {dstatus}")

                rack_csv_rows.append({
                    "Rack":        rack_name,
                    "Location":    rack_location,
                    "Rack Height": f"{rack_height}U",
                    "Rack Status": rack_status,
                    "RU Position": position,
                    "Device Name": name,
                    "Device Type": dtype,
                    "Status":      dstatus,
                })
        else:
            print("  No devices found in this rack.")

        print()

        # CSV export for rack device list
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        prompt_save_csv(
            rows             = rack_csv_rows,
            fieldnames       = [
                "Rack", "Location", "Rack Height", "Rack Status",
                "RU Position", "Device Name", "Device Type", "Status",
            ],
            default_filename = f"rack_{rack_name}_{timestamp}.csv",
        )

        input("\n  Press Enter to return to rack list...")


# =======================================================
# OPTION 4 — PLATFORMS
# =======================================================

def query_platforms(url, token):
    """
    Pull all platforms. Drill down into devices per platform (site filtered).
    Drill down further into device detail. CSV export at every level.
    """
    while True:
        print(f"\n[*] Fetching all platforms ...")

        platforms = api_get(url, token, "/api/dcim/platforms/",
                            params={"limit": 0})

        if not platforms:
            print("[!] No platforms found in Nautobot.")
            input("  Press Enter to return to menu...")
            return

        print(f"[+] Found {len(platforms)} platform(s).\n")
        divider()
        print(f"  {'#':<5} {'Platform Name':<30} {'Manufacturer'}")
        divider("-")

        platform_csv_rows = []
        for idx, platform in enumerate(platforms, start=1):
            name         = platform.get("name", "N/A")
            manufacturer = platform.get("manufacturer")
            manufacturer = manufacturer.get("name", "N/A") if manufacturer else "N/A"
            print(f"  {idx:<5} {name:<30} {manufacturer}")
            platform_csv_rows.append({
                "Platform Name": name,
                "Manufacturer":  manufacturer,
            })

        divider()

        # CSV export for platform list
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        prompt_save_csv(
            rows             = platform_csv_rows,
            fieldnames       = ["Platform Name", "Manufacturer"],
            default_filename = f"platforms_{timestamp}.csv",
        )

        # Platform selection
        print("\n  Enter a number to drill down into a platform,")
        choice = input("  or press Enter to return to menu: ").strip()

        if not choice:
            return

        if not choice.isdigit() or not (1 <= int(choice) <= len(platforms)):
            print(f"\n[!] Invalid selection. Enter a number between 1 and {len(platforms)}.")
            continue

        selected_platform = platforms[int(choice) - 1]
        platform_name     = selected_platform.get("name", "N/A")
        platform_slug     = selected_platform.get("slug") or selected_platform.get("name")

        # Drill into platform — devices filtered by site
        while True:
            print(f"\n[*] Fetching devices on platform: {platform_name} "
                  f"at site: {SITE_NAME} ...")

            devices = api_get(
                url, token,
                "/api/dcim/devices/",
                params={"platform": platform_slug, "site": SITE_NAME},
            )

            # Fallback without site filter
            if not devices:
                print(f"[!] No devices found at site: {SITE_NAME} for "
                      f"platform: {platform_name}")
                print(f"[*] Trying without site filter ...")
                devices = api_get(
                    url, token,
                    "/api/dcim/devices/",
                    params={"platform": platform_slug},
                )

            if not devices:
                print(f"[!] No devices found for platform: {platform_name}")
                input("  Press Enter to go back to platforms...")
                break

            print(f"[+] Found {len(devices)} device(s).\n")
            divider()
            print(f"  DEVICES ON PLATFORM: {platform_name}")
            print(f"  Site: {SITE_NAME}")
            divider("-")
            print(f"  {'#':<5} {'Device Name':<35} {'Status':<15} {'Rack'}")
            divider("-")

            platform_device_rows = []
            for idx, device in enumerate(devices, start=1):
                name   = device.get("name", "N/A")
                status = device.get("status", {}).get("label", "N/A")
                rack   = device.get("rack")
                rack   = rack.get("name", "N/A") if rack else "Not racked"
                print(f"  {idx:<5} {name:<35} {status:<15} {rack}")
                platform_device_rows.append({
                    "Platform":    platform_name,
                    "Device Name": name,
                    "Status":      status,
                    "Rack":        rack,
                })

            divider()

            # CSV export for platform device list
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            prompt_save_csv(
                rows             = platform_device_rows,
                fieldnames       = ["Platform", "Device Name", "Status", "Rack"],
                default_filename = f"platform_{platform_name}_{timestamp}.csv",
            )

            # Device drill-down
            print("\n  Enter a number to drill down into a device,")
            device_choice = input(
                "  or press Enter to go back to platforms: "
            ).strip()

            if not device_choice:
                break

            if not device_choice.isdigit() or \
               not (1 <= int(device_choice) <= len(devices)):
                print(f"\n[!] Invalid selection. Enter a number between "
                      f"1 and {len(devices)}.")
                continue

            selected_device = devices[int(device_choice) - 1]
            device_name     = selected_device.get("name", "N/A")
            print()
            detail_rows = display_device_detail(url, token, selected_device)

            # CSV export for device detail
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            prompt_save_csv(
                rows             = detail_rows,
                fieldnames       = DEVICE_DETAIL_FIELDS,
                default_filename = f"device_{device_name}_{timestamp}.csv",
            )

            input("\n  Press Enter to return to platform device list...")


# =======================================================
# OPTION 5 — SEARCH BY DEVICE NAME
# =======================================================

# Nautobot filter parameters for each match type
MATCH_TYPES = {
    "1": ("name__isw", "Starts with"),   # case-insensitive starts-with
    "2": ("name__ic",  "Contains"),      # case-insensitive contains
    "3": ("name",      "Exact"),         # exact match
}


def prompt_match_type():
    """
    Prompt the user once to select a match type.
    Returns (nautobot_param, label) tuple.
    e.g. ("name__isw", "Starts with")
    """
    print("\n  Match type:")
    print("  1. Starts with  — abc-  matches abc-spine-01, abc-leaf-01")
    print("  2. Contains     — spine matches abc-spine-01, dc-spine-02")
    print("  3. Exact        — full hostname only")
    divider("-")

    while True:
        choice = input("  Select match type (1/2/3): ").strip()
        if choice in MATCH_TYPES:
            param, label = MATCH_TYPES[choice]
            print(f"  [*] Using: {label}")
            return param, label
        print("  [!] Invalid — enter 1, 2, or 3.")


def search_devices_by_names(url, token, hostnames, match_param):
    """
    Shared lookup engine for Quick Search and File Search.

    For exact matches    — shows full device detail immediately.
    For partial matches  — shows a numbered summary list of all matches
                           per search term, then offers drill-down into
                           any device for full detail.

    Args:
        url         : Nautobot base URL
        token       : API token
        hostnames   : List of search terms
        match_param : Nautobot filter param — name, name__isw, or name__ic

    Returns a flat list of CSV-ready rows across all matched devices.
    """
    all_csv_rows = []
    found_count  = 0
    missing      = []
    is_exact     = match_param == "name"

    for term in hostnames:
        term = term.strip()
        if not term:
            continue

        print(f"\n[*] Searching: '{term}' ...")

        matched = api_get(url, token, "/api/dcim/devices/",
                          params={match_param: term, "limit": 0})

        if not matched:
            missing.append(term)
            print(f"  [!] No devices found for: {term}")
            continue

        found_count += len(matched)

        # -----------------------------------------------
        # Exact match — show full detail immediately
        # -----------------------------------------------
        if is_exact:
            rows = display_device_detail(url, token, matched[0])
            all_csv_rows.extend(rows)

        # -----------------------------------------------
        # Partial match — summary list first, then drill
        # -----------------------------------------------
        else:
            print(f"  [+] Found {len(matched)} match(es) for '{term}'.\n")
            divider()
            print(f"  {'#':<5} {'Device Name':<35} {'Status':<12} "
                  f"{'Platform':<20} {'Rack':<20} {'RU'}")
            divider("-")

            summary_rows = []
            for idx, device in enumerate(matched, start=1):
                name      = device.get("name", "N/A")
                status    = device.get("status", {}).get("label", "N/A")
                platform  = device.get("platform")
                platform  = platform.get("name", "N/A") if platform else "N/A"
                rack      = device.get("rack")
                rack_name = rack.get("name", "N/A") if rack else "Not racked"
                position  = str(device.get("position", "N/A"))
                primary_ip = device.get("primary_ip")
                primary_ip = primary_ip.get("address", "N/A") \
                             if primary_ip else "Not assigned"

                print(f"  {idx:<5} {name:<35} {status:<12} "
                      f"{platform:<20} {rack_name:<20} {position}")

                summary_rows.append({
                    "Device Name": name,
                    "Status":      status,
                    "Platform":    platform,
                    "Primary IP":  primary_ip,
                    "Rack":        rack_name,
                    "RU Position": position,
                })

            divider()

            # CSV export for this term's summary
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            prompt_save_csv(
                rows             = summary_rows,
                fieldnames       = [
                    "Device Name", "Status", "Platform",
                    "Primary IP", "Rack", "RU Position",
                ],
                default_filename = f"search_{term}_{timestamp}.csv",
            )

            # Drill-down into a specific match
            while True:
                print(f"\n  Enter a number to drill into a device,")
                drill = input(
                    "  or press Enter to continue to next search term: "
                ).strip()

                if not drill:
                    break

                if not drill.isdigit() or \
                   not (1 <= int(drill) <= len(matched)):
                    print(f"\n  [!] Invalid — enter a number between "
                          f"1 and {len(matched)}.")
                    continue

                selected    = matched[int(drill) - 1]
                device_name = selected.get("name", "N/A")
                print()
                detail_rows = display_device_detail(url, token, selected)
                all_csv_rows.extend(detail_rows)

                # CSV export for device detail
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                prompt_save_csv(
                    rows             = detail_rows,
                    fieldnames       = DEVICE_DETAIL_FIELDS,
                    default_filename = f"device_{device_name}_{timestamp}.csv",
                )

                input("\n  Press Enter to return to match list...")

    # Final summary
    divider()
    print(f"  Search complete.")
    print(f"  Matched : {found_count} device(s)")
    if missing:
        print(f"  No results for {len(missing)} term(s):")
        for m in missing:
            print(f"            - {m}")
    divider()

    return all_csv_rows


def query_search_by_name(url, token):
    """
    Sub-menu for searching devices by name.
    Two input methods:
        1. Quick Search — paste terms comma separated
        2. File Search  — load terms from a text file, one per line
    Match type selected once per search session:
        Starts with / Contains / Exact
    """
    while True:
        print("\n")
        divider()
        print("  Search by Device Name")
        divider()
        print("  1. Quick Search  — paste terms (comma separated)")
        print("  2. File Search   — load from text file (one per line)")
        print("  3. Back to main menu")
        divider()

        choice = input("  Select an option: ").strip()

        # ---------------------------------------------------
        # Quick Search
        # ---------------------------------------------------
        if choice == "1":
            print("\n  Paste search terms separated by commas.")
            raw = input("  Terms: ").strip()

            if not raw:
                print("  [!] No input provided.")
                continue

            terms = [t.strip() for t in raw.split(",") if t.strip()]

            if not terms:
                print("  [!] No valid terms found in input.")
                continue

            # Prompt for match type once
            match_param, match_label = prompt_match_type()

            print(f"\n[*] Quick Search — {len(terms)} term(s) "
                  f"using '{match_label}' matching.")

            all_csv_rows = search_devices_by_names(
                url, token, terms, match_param
            )

            # Final CSV export covering all terms
            if all_csv_rows:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                prompt_save_csv(
                    rows             = all_csv_rows,
                    fieldnames       = DEVICE_DETAIL_FIELDS,
                    default_filename = f"search_results_{timestamp}.csv",
                )

            input("\n  Press Enter to return to search menu...")

        # ---------------------------------------------------
        # File Search
        # ---------------------------------------------------
        elif choice == "2":
            print("\n  Enter the full path to your search terms file.")
            print("  File format: one term per line, # lines are ignored.")
            filepath = input("  File path: ").strip().strip('"')

            if not filepath:
                print("  [!] No file path provided.")
                continue

            if not os.path.exists(filepath):
                print(f"  [-] File not found: {filepath}")
                print("      Check the path and try again.")
                continue

            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    terms = [
                        line.strip()
                        for line in f.readlines()
                        if line.strip()
                        and not line.startswith("#")
                    ]
            except IOError as e:
                print(f"  [-] ERROR reading file: {e}")
                continue

            if not terms:
                print("  [!] File is empty or contains no valid terms.")
                continue

            # Prompt for match type once
            match_param, match_label = prompt_match_type()

            print(f"\n[*] File Search — {len(terms)} term(s) loaded "
                  f"from: {os.path.basename(filepath)} "
                  f"using '{match_label}' matching.")

            all_csv_rows = search_devices_by_names(
                url, token, terms, match_param
            )

            # Final CSV export covering all terms
            if all_csv_rows:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                prompt_save_csv(
                    rows             = all_csv_rows,
                    fieldnames       = DEVICE_DETAIL_FIELDS,
                    default_filename = f"search_results_{timestamp}.csv",
                )

            input("\n  Press Enter to return to search menu...")

        # ---------------------------------------------------
        # Back to main menu
        # ---------------------------------------------------
        elif choice == "3":
            return

        else:
            print("\n  [!] Invalid selection. Please enter 1, 2, or 3.")


# =======================================================
# MAIN MENU
# =======================================================

def main_menu():
    while True:
        print("\n")
        divider()
        print("  Nautobot Query Tool")
        print(f"  Site: {SITE_NAME}")
        divider()
        print("  1. Devices")
        print("  2. IP Addresses")
        print("  3. Racks")
        print("  4. Platforms")
        print("  5. Search by Device Name")
        print("  6. Exit")
        divider()

        choice = input("  Select an option: ").strip()

        if choice == "1":
            query_devices(url, token)
        elif choice == "2":
            query_ip_addresses(url, token)
        elif choice == "3":
            query_racks(url, token)
        elif choice == "4":
            query_platforms(url, token)
        elif choice == "5":
            query_search_by_name(url, token)
        elif choice == "6":
            print("\n  Goodbye.\n")
            sys.exit(0)
        else:
            print("\n  [!] Invalid selection. Please enter 1 through 6.")


# =======================================================
# ENTRY POINT
# =======================================================

if __name__ == "__main__":
    url, token = load_config()

    if not test_connection(url, token):
        print("[-] Could not connect to Nautobot. Check your config and network.")
        sys.exit(1)

    main_menu()
